// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	"context"

	"github.com/arielsrv/fxf/internal/features/messages/dtos"
	mock "github.com/stretchr/testify/mock"
)

// NewMockICreateMessageCommandHandler creates a new instance of MockICreateMessageCommandHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICreateMessageCommandHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICreateMessageCommandHandler {
	mock := &MockICreateMessageCommandHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockICreateMessageCommandHandler is an autogenerated mock type for the ICreateMessageCommandHandler type
type MockICreateMessageCommandHandler struct {
	mock.Mock
}

type MockICreateMessageCommandHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICreateMessageCommandHandler) EXPECT() *MockICreateMessageCommandHandler_Expecter {
	return &MockICreateMessageCommandHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockICreateMessageCommandHandler
func (_mock *MockICreateMessageCommandHandler) Handle(ctx context.Context, cmd *dtos.CreateMessageCommand) (*dtos.CreateMessageCommandResponse, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 *dtos.CreateMessageCommandResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dtos.CreateMessageCommand) (*dtos.CreateMessageCommandResponse, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dtos.CreateMessageCommand) *dtos.CreateMessageCommandResponse); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.CreateMessageCommandResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dtos.CreateMessageCommand) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICreateMessageCommandHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockICreateMessageCommandHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *dtos.CreateMessageCommand
func (_e *MockICreateMessageCommandHandler_Expecter) Handle(ctx interface{}, cmd interface{}) *MockICreateMessageCommandHandler_Handle_Call {
	return &MockICreateMessageCommandHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, cmd)}
}

func (_c *MockICreateMessageCommandHandler_Handle_Call) Run(run func(ctx context.Context, cmd *dtos.CreateMessageCommand)) *MockICreateMessageCommandHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dtos.CreateMessageCommand
		if args[1] != nil {
			arg1 = args[1].(*dtos.CreateMessageCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICreateMessageCommandHandler_Handle_Call) Return(createMessageCommandResponse *dtos.CreateMessageCommandResponse, err error) *MockICreateMessageCommandHandler_Handle_Call {
	_c.Call.Return(createMessageCommandResponse, err)
	return _c
}

func (_c *MockICreateMessageCommandHandler_Handle_Call) RunAndReturn(run func(ctx context.Context, cmd *dtos.CreateMessageCommand) (*dtos.CreateMessageCommandResponse, error)) *MockICreateMessageCommandHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}
